version: "3.8"

services:
  postgres:
    container_name: compare-pg
    image: bitnami/postgresql
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - db:/data/db
    networks:
      - compare-watch-networks
  api:
    build: 
      dockerfile: ./dockerfile
      context: .
    image: compare-watch-api
    container_name: compare-watch-api
    depends_on:
      - postgres
    links:
      - postgres
    env_file: ./.env
    ports:
      - 3333:3333
    networks:
      - compare-watch-networks

volumes:
  db:

networks:
  compare-watch-networks:
    driver: bridge

